### ISSUE TITLE
aws gdal arn usage with python lambda

### ISSUE THREAD

**Issue by ewirth** [lambgeo/docker-lambda#12]
Hi, 
I am just a starter AWS user, successfully added your GDAL ARN (west-2) to my lambda function called geostats as a layer, 
but if I try to import the gdal package, I have an error:
#import gdal
#from osgeo import gdal

What else I have to do to make it work?

**Comment by vincentsarago** [comment]
Hi @ewirth, 
GDAL lambda layer is not shipped with gdal python bindings, you'll need to have it installed in your package see https://github.com/lambgeo/docker-lambda#2-use-lambda-layer-see-exampleslayer

**Comment by ManishSahu53** [comment]
I tried with pip install gdal, but still unable to use
1. import gdal
2. from osgeo import gdal

Error : `No module named '_gdal`

**Comment by vincentsarago** [comment]
can you give a bit more description please ?

**Comment by ManishSahu53** [comment]
I am using layer - `arn:aws:lambda:us-west-1:524387336408:layer:gdal32:1`
with tutorial - `https://github.com/lambgeo/docker-lambda#2-advanced-need-other-python-dependencies`

using python 3.8 also
I am trying to use gdal itself in my application
I have put gdal in requirements.txt and build the docker
Inside, i can do `from osgeo import gdal`
but when upload to aws lambda, above error is coming.

**Comment by BasemHamad** [comment]
how did fix this ?

**Comment by nghilethanh09052000** [comment]
Anyone fix it l?
