### ISSUE TITLE
psql: undefined symbol: PQsetErrorContextVisibility

### ISSUE THREAD

**Issue by kikeh** [lambgeo/docker-lambda#13]
Hi, I love the idea of using GDAL as a layer for lambdas and I have been doing some tests with it lately and it has been working fine. However, recently I was starting one of my projects locally from the scratch and got this error when connecting my app backend (Django) to the database:

```sh
psql: symbol lookup error: psql: undefined symbol: PQsetErrorContextVisibility
```

I am able to access the database container and use `psql` without a problem, the issue seems to happen from the container that uses the `lambgeo/lambda:gdalX.X-py3.7` image.

What I have been finding about this error around the internet, it is that it's caused from an unsupported version, not finding the symbol `PQsetErrorContextVisibility` as stated. 

Any idea as why this is happening? (and why it wasn't when I wasn't using a new database?)

**Comment by vincentsarago** [comment]
stale, please provide full runable example if this still exist with the latest version
