### ISSUE TITLE
Can we get DXF vector drivers?

### ISSUE THREAD

**Issue by hugozaggo** [lambgeo/docker-lambda#42]
I am trying to use ogr2ogr on a lambda layer but it looks like the DXF driver is missing.
Is there any way to get it? I can't figure out how to build a docker image with DXF vector support (so I could later make a layer package of it). [https://gdal.org/drivers/vector/dxf.html#vector-dxf](https://gdal.org/drivers/vector/dxf.html#vector-dxf) states it is built-in, so I figured it should be supported by default

Running `ogrinfo --formats` on lambgeo/lambda-gdal:3.3-al2 does not list it, though

```bash
# ogrinfo --formats
Supported Formats:
  netCDF -raster,multidimensional raster,vector- (rw+vs): Network Common Data Format
  PDS4 -raster,vector- (rw+vs): NASA Planetary Data System 4
  VICAR -raster,vector- (rw+v): MIPL VICAR file
  JP2OpenJPEG -raster,vector- (rwv): JPEG-2000 driver based on OpenJPEG library
  MBTiles -raster,vector- (rw+v): MBTiles
  BAG -raster,multidimensional raster,vector- (rw+v): Bathymetry Attributed Grid
  ESRI Shapefile -vector- (rw+v): ESRI Shapefile
  MapInfo File -vector- (rw+v): MapInfo File
  OGR_VRT -vector- (rov): VRT - Virtual Datasource
  Memory -vector- (rw+): Memory
  GML -vector- (rw+v): Geography Markup Language (GML)
  KML -vector- (rw+v): Keyhole Markup Language (KML)
  GeoJSON -vector- (rw+v): GeoJSON
  GeoJSONSeq -vector- (rw+v): GeoJSON Sequence
  ESRIJSON -vector- (rov): ESRIJSON
  TopoJSON -vector- (rov): TopoJSON
  GPKG -raster,vector- (rw+vs): GeoPackage
  SQLite -vector- (rw+v): SQLite / Spatialite
  PostgreSQL -vector- (rw+): PostgreSQL/PostGIS
  FlatGeobuf -vector- (rw+v): FlatGeobuf
  PGDUMP -vector- (w+v): PostgreSQL SQL dump
  OGR_PDS -vector- (rov): Planetary Data Systems TABLE
  MVT -vector- (rw+v): Mapbox Vector Tiles
```

Any info is appreciated, and thank you for lambgeo/docker-lambda!

**Comment by hugozaggo** [comment]
Oh, maybe --enable-driver-dxf (or remove --disable-all-optional-drivers).

I think I missed it before. I'll try this later and report back in case someone else has the same question.

**Comment by hugozaggo** [comment]
--enable-driver-dxf did it

**Comment by vincentsarago** [comment]
@hugozaggo feel free to open a PR to add it in the `official` image

**Comment by vincentsarago** [comment]
Docker images and lambda layers have been updated, make sure to use the latest lambda layer version! 
🙏 for this nice contribution
