### ISSUE TITLE
Trouble using lambda layers (python 3.9 / gdal 3.5)

### ISSUE THREAD

**Issue by bo-lu** [lambgeo/docker-lambda#49]
Not quite sure what I'm missing when trying to use that the layer arn: `arn:aws:lambda:ca-central-1:524387336408:layer:gdal35:3` on **ca-central-1** based on this [list](https://github.com/lambgeo/docker-lambda/blob/master/layer.json#L557)

I tried to import numpy and rasterio which both failed as well. Finally, if I add the aws-data-wrangler layer, I am able to `import numpy` without error.

<img width="612" alt="gdal-layer" src="https://user-images.githubusercontent.com/18405829/180859898-4dc4281e-64cc-4b5b-a60c-2735e3d56c45.png">

**Comment by vincentsarago** [comment]
The GDAL35 layer has no python module, just GDAL C libraries. You need to create your own `runtime` layer/package using https://github.com/lambgeo/docker-lambda#2-advanced-need-other-dependencies

**Comment by bo-lu** [comment]
I took at the GDAL35 layer and it doesn't look like it was installed with the python bindings to support `from osgeo import gdal` anyway. Is that correct?

**Comment by vincentsarago** [comment]
> The GDAL35 layer has **no python module, just GDAL C libraries**.
