### ISSUE TITLE
Invoking lambda always throws "No module named 'osgeo' "

### ISSUE THREAD

**Issue by abdul-imran** [lambgeo/docker-lambda#59]
My lambda is is us-west-1 region & I'm using the layer `arn:aws:lambda:us-west-1:524387336408:layer:gdal32-python38-geo:1`
I have also created the 2 environment variables **GDAL_DATA** and **PROJ_LIB**
The only thing my lambda does is importing gdal as `from osgeo import gdal`

When this lambda is executed, I get the below error
`{`
`  "errorMessage": "Unable to import module 'handler': No module named 'osgeo'",`      
`  "errorType": "Runtime.ImportModuleError",`
`  "stackTrace": []`
`}`

I have tried using Python 7 & 8 7 still see the same error.
Am I missing something? Please help me. Thanks

**Comment by vincentsarago** [comment]
the layer do no provide the python GDAL bindings, you need to create your own package https://github.com/lambgeo/docker-lambda#2-advanced-need-other-dependencies
